language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- cd client && npm run build
deploy:
  provider: heroku
  app: utility-site
  api_key:
    secure: Y4u9VJ6EDJ9S+D6XJhI4lW7aUOTY+EdaHue9h7Y7vebxZVAJu80pt0LYMBSlKmuE3alnbWM3d03lQBUdoEqz0ZuhooZhmPmxlaR6Lw1wmkhUG2LK8nhGQ17kScn2zbIL0/CeeJQoQGrXHU0zeY4bUi7ehAN4B4pCXXFYPnyUt5j0y+sdZEvIH2rOSsFMqVBVCc+kyH3x10rvwiSSTVl6udptlRUhVl9RWeTRa3n8WL3aips3o4tjJ9Q4+SvJHzERsp3tHFGemCmsfmeuBU5r9NRpUTgjxo4n2YUXWkacSCnORv3B6L6aGae23eiSMATeRxalSRgYt4u+jGk5kPJ7EWpu5FGMRqEXwqWFz4cnJSg7cUqUiU92pjWHhPwPOyyQdxhiFjFg8xXdFTNrSwaWrS18O/BwDPCHAEgF+LVWkkLC1HVxSj3/BhwjRZ89tIknGLSxpRX4wCdh2Q2bz3SbU94kqsxFJaDwxsMELsZkPkucPIOt81qTBG3gUkXOycrSQ39lsKuKtW+9g84IL3+K/ufX9BFbe/PRPWchMjDumOBKm24AAOiQ/88yKh1zRS4kxcKRv4t1bS1K2z2Q1At/Zn/L3WszAq/eje6CMYvOwR8lpWqcU0gcLxpYmghdsL4d2fKxQ0TbV0PIcRuT81/gjqEOGCVGtao++yFQammIgoA=
  on:
    repo: Tiico/Utility-Site
    branch: master
