language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- cd client
- npm i
- npm run build
deploy:
  provider: heroku
  app: utility-site
  api_key:
    secure: PTLvnrQ7OLckSxfslDQsxNAKYintJKTE26SLgd56diQ29296n6UwzftwuGHHOEvoHMWkkYuG244UZ/yQ13sdDUyw8v9ujwS5RkjSHrX64NHq+rfdEcjmXiHGG22eekPUAaN8w22nWYSswrBzS+mCFnl1gnu8jpJLJBrWOWXEkdLJmsDiGLY2fskfj13zC3yw1oi7kk/8bqrV6yDuVFYtlDrXP5OeZJeWyOldWgN/F/SqN0c8/Szrl12CNw1RfT/Orx2AMVw/M+8OAsajZdNSE25Rm4az3ws14vSYGHVaQeAxgZhGs7InTekfrtAbnkHl/VJCLn/SxrFOKdeUjOmyu+nb3h4aNs60gdbqKx/PRqDKZNEtqCf1gu2EUUnkepF65fMrj/IAqIyVj+eqaG21ZqIhwgF+pgyHObyBM69oWrcIoqQ2aSKdCAdypi+5rKq2OqUmLIFc1gMRaUcobMV08HM4Kdx0yD6PSUNxMVqyxnc6sptXs6R18C9IGI24g7pYop53glTcEb+UnBVIkGirYwB3v2sKKBWZ+KQHWsFesrVmKxQJj8LdOKhdTgFzWGMsHAoWuczxX8ltAs5F8oDWgsSnP74RqlSMRbnASMowQDOA5dmPkdkx+bRMM8f0RDiyZ0ut5XATiN5yr66aO2KlLzhgS16tYjCF2rQtBwCQTJ0=
  on:
    repo: Tiico/Utility-Site
    branch: master
