language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- cd client
- npm i
- npm run build
deploy:
  provider: heroku
  app: utility-site
  api_key:
    secure: jtosDZ/sPVj5XphFmc5Bvu6/UAaqRb+Fn/1lZfo3wwlzHjyZncKQhpGofaSxRK3Yo2v2ji51uF/0d7ZNwIrKb1lDFofM8cdCkMyDPzhSjdokaTNiONLwdg+ne2lkMJhONCqI+Vn5xbU4gaZH9cYe2fUNPHoDtxhmZAhlyhNri1Ca58kxunpyRGq2anMfnjX3CkNZRbx0OTng7aV/BCmbLWX6iM3Prbbrc2kC36d+6zJWnpV8GKC5pkxIpg56i7S/88Ygvpcyke2Woo/qhWCURJWuO/r5audXNrDfn90KWG8vWWooRiAoF3GAKzzonf1cWmmhID8f4PyHKDi6XQU4I9LE2MJiYOkXthOp5DkwtEei8O5FzORFxZTSq50YpTLhMQAlGr6cCL/y9K9+opBWKIqep4x309RCf0xkzp5maGZ5CC+3BypzJPan0V1U5DPn1GZ6ZxSSFl0KaGJFS65VlejcaCuFa1V9PPin9uiFDyzrDWYBhAznBjzusxzvkDyoR9fMMq+xJwhJW+o/168qv4yMhyA9B4W8GeSvh/OKq5metfjNFcQP5usnI3zagZ0JE6jMitLoDFtQ+KWD1j8zwNe+Kl9PqWrHaetYoOTmQYsXXj0sVNzae16/U5qOCxgl3hC+KtfTs01m7G+rpucQkN2ZE7cyDEGV+y7YdqH2pSo=
  on:
    repo: Tiico/Utility-Site
    branch: master
