language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- cd client
- npm i
- npm run build
deploy:
  provider: heroku
  app: utility-site
  api_key:
    secure: H0L8hoi/YE/k1FxZgAy0Iwq3IPpK+vlmOYzdZDlJ/yxMmEfSAfBbtkhH2v9MPmIzJeZhMl4UJFkzW23icTYlHexUVwQGTVUbr8kHel2jXBCuBB7rbK3ptsQgWo+k4AxrCXEaZg4ibIgxTsXAoLUaUrQCaGzyzaSj/2NXIr8KSUnlPIP/xtxsTRmvQJuGyNjCSwHz2uZKPvWOxCaw3K9Hd4N5jWkcT6IvwR6/haGhts+6andQdg9H3ctMwMfUnMp5ebVHAf2xvmHACQU2r2IJ74yo68MCv3Ttr8QNHBKmeVQqkNzpm62cf1e7htVO98aJoGxCS9FpAdLcEkYHVjB9a67D1OCJPqZtlYsi7NoJ3l0dbbBvTaj0IhlTFaZzh8JZCaZ/TSoUiWOFIgjRYLMRpGyBd2UCw7VBDKqGKSHyv9Ik66TUppU4ZOF9rNIxkovNiTZGhQ1dyBhwZQJrmuXqbTFrIGdtzWoblqbh7gU1OaxR7C2qtpUi4Y+LPp1p59t/ePjjxi0qaalNxAGLlrFL9YzdxS5LN/gGx8e1qzWEbIX8FloiOynr3yO/MCdhxQtSDzbs6J3L7Z7iuo+6sJkqtUFkoKikFTOpXv67onvmIELUcfUHcWTwJI8WKpag2mcRzqHQH07jw+G7N2r3doEA0c7iR3cOoiS4tiG568CJnPA=
  on:
    repo: Tiico/Utility-Site
    branch: master
