language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: Utility-App
  on:
    repo: Tiico/Utility-Site
    branch: master
  api_key:
    secure: c+6luzDva4zas8FpDVhtyZJyuPtV0P9QXq0O97EdQPFc9dHKA0rpOdk4dNexLfWXoXRtNrQgNmb9zedo/6uPe4WNdZf60/vytrPFU3qTY0DbD7P96HFGOkWvYl9IMB8k4l3N9CRuxRfbdf7gsGVsDv77IMAZuesX196ptpgr1UktgVmCvot8GayG//+UDKzj7NCtYHr3kL2U4LUQI88lvQGxpDBNh1WTMjuspTSIkE/+r2fMUGzHHYIOrWdOmjaUBj0SW4sXb4B4NcFZDExDJVp/avknDrvrWSNbG9eDFsnFTAIAKVbT1gzfwnbqDobrunwbQkHxyp0shUVP79AyeoFrVuJANvWN8ZZCdMKFKOOJiK2e8PbAAoFmUsbshfjqLR55XpDhbnBZdWNC18CUU/AVWOP3mwB4Nr//tiSfdxOhBRZT6YucvKTaJjl7pq5EXPv/KOHfwCnesvH5V5KVWmtqEE7m4mUqZT0hU+BY6lTUd3c1YdJg7Z2PSQYhG26KSbvvWzi16l6QbaFFspnd90rZXP7IEo3I10FQEp2i9xzaBUinYHgqbrcWRd4218dZ56p2kD0HkGl9LALjf5xi+JlN5fx7AUCIQ0crMOPxeZObUwIb+xe7TMP/FwxwPAGVBi6DO7INPXjIAql5PuJJCJ+c45Uu6conLd9bWndMSHg=
